[WIP] Json schema templates
sustainable-computing-io/carbon-aware-scaling-poc pull request #2
Opened 2022-09-21 16:15 UTC by husky-parul

This PR adds schema templates for carbon intensity and power breakdown for the two back ends namely national grid eso and electrycitymaps

Signed-off-by: Parul <parsingh@redhat.com>

2022-09-21 16:20 UTC, husky-parul commented
@rootfs For the carbon intensity schema, the date we get from [electricity map](https://static.electricitymaps.com/api/docs/index.html#live-carbon-intensity) contains Zone information but [ngeso](https://data.nationalgrideso.com/carbon-intensity1/historic-generation-mix) does not. 

For our POC we definitely need zone wise information of carbon intensity. Two possible approach:
1. Use electricitymap for zone data
2. Add mock zone information to ngeso data

2022-09-21 16:33 UTC, rootfs commented
mock zone it is

2022-09-21 17:27 UTC, KaiyiLiu1234 requested changes
Nice WIP. Just to note, ngeso_schema is a nested json with zone and history. The example ngeso for carbon intensity only shows history. Might be good idea in follow up commit to include a complete example. electricitymap_schema is missing. From the example provided, it looks like all you need to do is define a schema with 7 properties (zone, carbonIntensity, datetime, updatedAt, emissionFactorType, isEstimated, estimationMethod). Include that in followup commit. One thing I am confused about is the power breakdown. It seems basically the same as carbon_intensity. Is there a reason for this? If I misunderstood anything let me know. If all of these are to be expected, I will approve the request and you can followup additional schema changes in future PRs.

2022-09-21 17:58 UTC, rootfs commented
would you please also add a README listing the origins of the data sources?

2022-09-21 18:46 UTC, husky-parul commented
After analyzing all public data from various sources it is clear that these data are not relevant for scaling/scheduling decisions for reasons:
1. the data is historic both electricitymap and ngeso
2. ngeso has only historic carbon intensity and power breakdown data dating Jan 2022. ngeso is aslo only for England

Without question we need a ML trained model to forecast zone wise carbon intensity for upcoming days. The json schema should then define the properties/features/metrics for training the model and also as Prometheus metrics. 

For now we can have `zone`, `carbonIntensity`, `datetime` as it is consistent across electricitymap an [ngeso](https://data.nationalgrideso.com/carbon-intensity1/regional-carbon-intensity-forecast/r/regional_carbon_intensity_forecast)
I will make the changes to the PR
cc: @rootfs @KaiyiLiu1234

2022-09-21 18:54 UTC, KaiyiLiu1234 commented
I am planning to make a PR for the carbon forecast end of today. I work will be on the carbon-forecast branch.

2022-09-21 19:36 UTC, yelghali commented
> After analyzing all public data from various sources it is clear that these data are not relevant for scaling/scheduling decisions for reasons:
> 
> 1. the data is historic both electricitymap and ngeso
> 2. ngeso has only historic carbon intensity and power breakdown data dating Jan 2022. ngeso is aslo only for England
> 
> Without question we need a ML trained model to forecast zone wise carbon intensity for upcoming days. The json schema should then define the properties/features/metrics for training the model and also as Prometheus metrics.
> 
> For now we can have `zone`, `carbonIntensity`, `datetime` as it is consistent across electricitymap and [ngeso](https://data.nationalgrideso.com/carbon-intensity1/regional-carbon-intensity-forecast/r/regional_carbon_intensity_forecast) I will make the changes to the PR cc: @rootfs @KaiyiLiu1234


hello team @KaiyiLiu1234 @husky-parul, 
2 small points:
* to do carbon aware scaling, we need current / actual emissions, not forecast data
* we could use forecast for a more advanced scenario: which is predictive scaling

and to get the forecast data, we don"t actually need to build an ML model 
from a study we did, we identified on our side the 2 main API providers (in term of functionnalities & country coverage):
* WattTim
* ElectricityMap
--> both provide forecasting

In term of common schema, we are trying to build a common interface for different providers. 

for power metrics: we don"t have a common spec (from my research)
for Carbon Intensity metrics:  This is what the GSF project is doing (part of Linux foundation)
https://github.com/Green-Software-Foundation/carbon-aware-sdk 

maybe we should build on what is existing

2022-09-21 20:00 UTC, rootfs commented
Hey @yelghali 
> * to do carbon aware scaling, we need live / actual emissions, not forecast data

per [discussion](https://github.com/sustainable-computing-io/carbon-aware-scaling-poc/blob/main/Meeting-note.md#items), forecast data is for time shifting (cron job) use case 

> * we could use forecast for a more advanced scenario: which is predictive scaling
> 

Let's have that in the demo :D 

> and to get the forecast data, we don"t actually need to build an ML model from a study we did, we identified on our side the 2 main API providers (in term of functionnalities & country coverage):
> 
> * WattTime: https://www.watttime.org/api-documentation/#emissions-forecast  (best for US coverage)
> * ElectricityMap : https://static.electricitymaps.com/api/docs/index.html#forecasted-marginal-carbon-intensity  (for EU)
>   --> both provide forecasting

Agreed, the forecast data are provided yet there are gaps: the forecast intervals are fixed (1 hour or 1 day), using that fixed intervals is not for general purpose planning. 
 
> In term of common schema, we are trying to build a common interface for different providers.
> 

This is great! We should make that available in reusable packages (which is also the goal of this PoC)

> * for power metrics: we don"t have a common spec (from my understanding)
> * for Marginal Carbon Intensity metrics:  This is what the GSF project is doing (part of Linux foundation)
>   https://github.com/Green-Software-Foundation/carbon-aware-sdk

The SDK can be nicer if it can be provided as a software package, in addition to WebApi, so it can be embeded in other frontend integrations, e.g. Prometheus. As discussed, this PoC is towards that direction.

>   --> The Sdk also handles the notion of Availability zones
> 
> maybe we should build on what is existing

This is a good start. As we discussed, this PoC is to investigate what is missing and provide evidence for future investigation. We'll see if that can address our use cases.

2022-09-21 20:06 UTC, yelghali commented
I see ok, let's keep exploring 
> per [discussion](https://github.com/sustainable-computing-io/carbon-aware-scaling-poc/blob/main/Meeting-note.md#items), forecast data is for time shifting (cron job) use case
> yes indeed, time shifting would be another sustainability pattern, that we discussed during the meeting, but I think it's outside of Keda scope.
--> which opens the discussion about common behaviors for sustainability actions (for example, they are triggered by carbon related  events / or alerts, they implement a pattern, send some events, etc.)

> > * we could use forecast for a more advanced scenario: which is predictive scaling
> 
> Let's have that in the demo :D
> Go ! i like ambition :d 

> and yes the sdk can be provided as a package (it is one), the current code sdk language is c# ; with several API client libraries (open api clients) with multiple languages

> This is a good start. As we discussed, this PoC is to investigate what is missing and provide evidence for future investigation. We'll see if that can address our use cases.
ok

2022-09-23 15:30 UTC, husky-parul commented
WattTime gives the carbon intensity of grid regions you have access to and not all the grid regions covered by WattTime. For e.g I have only access to `CAISO_NORTH`. It might not work as we can't track other grids carbon intensity hence how to determine best grid for scaling?

I have also realized that every back end has it's rules to compute carbon intensity which is not consistent across that back ends. In this case how does the carbon intensity value in Prometheus compares to each other when scraped from different back ends?

I might also suggest using a sink to persist data scraped from backend apis. All of the apis have restriction on number of queries made in day/hour/second. Live querying the API and pushing to Prometheus does not appear very efficient to me.

2022-09-23 17:32 UTC, rootfs commented on app/src/handlers/co2signal_handler.py
> +        self.HEADERS = {'auth-token': 'TKp6W1jGxm31TLCVIXpMfcTsS5yFALLu'}
read the token from config

2022-09-23 19:50 UTC, KaiyiLiu1234 commented
For forecast model, I think four good models I am setting up include ARIMA, SARIMA, Tensorflow NN, XGBoost regressor. ARIMA and SARIMA are currently the most popular for time series forecast. We can give these a test run with some data.

2022-09-30 17:28 UTC, rootfs commented
@husky-parul is it ready to go?

2022-10-03 12:19 UTC, husky-parul commented
@rootfs I will sync with upstream and apply for merge

2022-10-03 13:29 UTC, husky-parul commented
> Nice WIP. Just to note, ngeso_schema is a nested json with zone and history. The example ngeso for carbon intensity only shows history. Might be good idea in follow up commit to include a complete example. electricitymap_schema is missing. From the example provided, it looks like all you need to do is define a schema with 7 properties (zone, carbonIntensity, datetime, updatedAt, emissionFactorType, isEstimated, estimationMethod). Include that in followup commit. One thing I am confused about is the power breakdown. It seems basically the same as carbon_intensity. Is there a reason for this? If I misunderstood anything let me know. If all of these are to be expected, I will approve the request and you can followup additional schema changes in future PRs.

@KaiyiLiu1234 @rootfs we have a single scheme for carbon_intensity irrespective of the API/source. Could you review/approve if it looks good.

2022-10-03 13:36 UTC, rootfs approved these changes

2022-10-03 13:57 UTC, KaiyiLiu1234 approved these changes

2022-10-03 13:58 UTC, merged